#!/usr/bin/env node


var operator = process.argv[2];
var num1 = parseFloat(process.argv[3]); //makes input a number and not a string
var num2 = parseFloat(process.argv[4]);

if (isNaN(num1)){
	console.log("Please enter numbers only")
}

else if (isNaN(num2)){
	console.log("Please enter numbers only")
}

else{
	if (operator == "add" || operator == "+"){
		var answer = num1 + num2;
		console.log("= " + answer);
	}

	else if (operator == "subtract" || operator == "-"){
		var answer = num1 - num2;
		console.log("= " + answer);
	}

	else if (operator == "multiply" || operator == "*"){
		var answer = num1 * num2;
		console.log("= " + answer);
	}

	else if (operator == "divide" || operator == "/"){
		if ( num2 == 0){
			console.log("Cannot divide by 0"); 
		}
		else{	
			var answer = num1 / num2;
			console.log("= " + answer);
		}
	}

	else {
		console.log("Typo. Please start over");
	}
}
