#!/usr/bin/env node


var operator = process.argv[2];
var one = new Number(process.argv[3]); //new Number() processes argument as number and not a string
var two = new Number(process.argv[4]);


if (operator == "add"){
	var answer = one + two;
	console.log("= " + answer);
}

else if (operator == "subtract"){
	var answer = one - two;
	console.log("= " + answer);
}

else if (operator == "multiply"){
	var answer = one * two;
	console.log("= " + answer);
}

else if (operator == "divide"){
	if ( two == 0){
		console.log("Cannot divide by 0"); 
	}
	else{	
		var answer = one / two;
		console.log("= " + answer);
	}
}

else {
	console.log("Typo. Please start over");
}
